### PR TITLE
Time splitting

### LINKED ISSUE #1: Fix slice rules to check for type and show hints
Currently `sliceRules` does not work

### LINKED ISSUE #2: Fix selectedRange
`selectedRange` is not responsive to the time input selection
I think it needs a watchEffect?

### PR DESCRIPTION
**Pull request by gotdairyya**
### Does this PR close any open issues?
Closes #2 
Closes #1 

### Give a longer description of what this PR addresses and why it's needed
This PR allows the user to split the network according to a set number of time slices.

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [x] Filter network based on the edge attribute selections

### CODE REVIEW

**Comment by gotdairyya** [comment]
Add #5 because I think it is premature to do the additional filtering especially since we will have access to that information

File: src/types.ts [hunk 1]
```diff
@@ -71,7 +72,15 @@ export interface AttributeRanges {
   [key: string]: AttributeRange;
 }
 
+export interface SlicedNetworks {
```
Comment (JackWilb) [inline src/types.ts]: This should probably be `SlicedNetwork`, since it's just one object

File: src/App.vue [hunk 2]
```diff
@@ -65,6 +69,9 @@ export default {
   <v-app>
     <v-main>
       <controls />
+      <time-line
+        v-if="network !== null && slicedNetwork === true"
```
Comment (JackWilb) [inline src/App.vue]:
```suggestion
        v-if="network !== null && slicedNetwork"
```

File: src/components/DragTarget.vue [hunk 3]
```diff
@@ -49,12 +49,25 @@ export default defineComponent({
...
           color: edgeVariables.value.color,
+          time: edgeVariables.value.time,
         };
         store.commit.setEdgeVariables(updatedEdgeVars);
       } else if (props.type === 'edge' && props.title === 'color') {
         const updatedEdgeVars = {
           width: edgeVariables.value.width,
           color: droppedVarName,
+          time: edgeVariables.value.time,
+
```
Comment (JackWilb) [inline src/components/DragTarget.vue]: Extra blank line to remove

File: src/components/TimeLine.vue [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+import {
+  computed, defineComponent, ref, Ref, watch,
+} from '@vue/composition-api';
+
+export default defineComponent({
+  name: 'TimeLine',
+
+  setup() {
+    const slicedNetwork = computed(() => store.state.slicedNetwork);
+    const svg: Ref<Element | null> = ref(null);
```
Comment (JackWilb) [inline src/components/TimeLine.vue]: This isn't needed and can be removed throughout

File: src/components/TimeLine.vue [hunk 5]
```diff
@@ -0,0 +1,147 @@
...
+      currentTime.value.current = selection;
+      selectAll('.timelineRectClass').classed('selected', false);
+      select(`#timeSlice_${selection}`).classed('selected', true);
+
+      store.commit.setNetwork(slicedNetwork.value[selection].network);
+    }
+
+    watch([slicedNetwork], () => {
+      selectAll('.timelineRectClass').classed('selected', false);
+      select('#timeSlice_0').classed('selected', true);
```
Comment (JackWilb) [inline src/components/TimeLine.vue]: We could just set currentTime.current here

File: src/components/TimeSlicing.vue [hunk 6]
```diff
@@ -0,0 +1,263 @@
...
+  computed, defineComponent, ref, watch,
+} from '@vue/composition-api';
+
+export default defineComponent({
+  name: 'TimeSlicing',
+
+  setup() {
+    const showOptions = ref(false);
+    // eslint-disable-next-line no-restricted-globals
+    const sliceRules = (value: string) => !isNaN(parseFloat(value)) || 'Please type a number';
```
Comment (JackWilb) [inline src/components/TimeSlicing.vue]: We can use number.isNaN here and remove the eslint disable, I think

File: src/components/TimeSlicing.vue [hunk 7]
```diff
@@ -0,0 +1,263 @@
...
+      }
+      return range;
+    });
+
+    const timeMin = computed(() => timeRange.value[0]);
+    const timeMax = computed(() => timeRange.value[1]);
+
+    const selectedRange = ref([0, 0]);
+
+    watch([timeMax], () => {
```
Comment (JackWilb) [inline src/components/TimeSlicing.vue]: Would this not update for a `timeMin` change?

File: src/components/TimeSlicing.vue [hunk 8]
```diff
@@ -0,0 +1,263 @@
...
+      let networkToReturn: SlicedNetworks[] = [];
+
+      // Resets to original network view
+      if (originalNetwork.value !== null) {
+        if (timeSliceNumber.value === 1) {
+          store.commit.setSlicedNetwork(networkToReturn);
+          store.commit.setNetwork(originalNetwork.value);
+          return networkToReturn;
+        }
+        if (originalNetwork.value !== null) {
```
Comment (JackWilb) [inline src/components/TimeSlicing.vue]: This check is duplicated, is it complaining if you remove this if statement?

File: src/components/TimeSlicing.vue [hunk 9]
```diff
@@ -0,0 +1,263 @@
...
+          networkToReturn = slicedNetwork;
+
+          store.commit.setSlicedNetwork(networkToReturn);
+          store.commit.setNetwork(networkToReturn[0].network);
+          return networkToReturn;
+        }
+        store.commit.setSlicedNetwork(networkToReturn);
+        return networkToReturn;
+      }
+      return networkToReturn;
```
Comment (JackWilb) [inline src/components/TimeSlicing.vue]: There are a ton of different places where you can return from this function, which makes it tricky to read and follow. Could you try refactoring this so that there is just one return statement? You'd use more if statements in the body to manage the flow and then at the end, just return the `networkToReturn` after all the ifs

File: src/components/TimeSlicing.vue [hunk 10]
```diff
@@ -0,0 +1,263 @@
...
+        <v-list-item>
+          <v-row>
+            <v-col>
+              <v-btn
+                color="primary"
+                block
+                depressed
+                @click="sliceNetwork"
+              >
+                Generate Slices
```
Comment (JackWilb) [inline src/components/TimeSlicing.vue:235]: Is generating the slices a manual process? Should we instead have it trigger on page load or when we fetch the network in the store?

File: src/components/EdgeBuilder.vue [hunk 11]
```diff
@@ -0,0 +1,142 @@
...
+  position: sticky;
+  top: 0;
+  z-index: 2;
+  background-color: white;
+}
+
+.draggable {
+  cursor: pointer;
+}
+</style>
```
Comment (JackWilb) [inline src/components/EdgeBuilder.vue:142]: I wonder if there's a lot of duplication going here that will make these components harder to maintain. I'm not sure there's anything to do here for now, but maybe we should open an issue to fix it up later

File: src/components/EdgeBuilderChart.vue [hunk 12]
```diff
@@ -0,0 +1,601 @@
...
+  float: right;
+}
+
+.label {
+  max-width: 110px;
+  overflow: hidden;
+  text-overflow: ellipsis;
+}
+
+</style>
```
Comment (JackWilb) [inline src/components/EdgeBuilderChart.vue:601]: What changed in this component to make it different to legend chart?

**Comment by JackWilb** [comment]
Looks like a good start. I'm interested to see if we can simplify the code a little, by reusing code for the controls and legend charts in a smarter way. If you have time to do some digging, that'd be awesome. If not, we can keep a note of it for the future, but we will be accruing some technical debt.

I'm requesting changes for the small changes and to see how you feel about removing some of the duplicated code. Let me know what you think

**Review by JackWilb — CHANGES_REQUESTED** [review]

File: src/types.ts (hunk 1 above)
Comment (gotdairyya) [reply src/types.ts]: Changed

File: src/components/TimeLine.vue (hunk 4 above)
Comment (gotdairyya) [reply src/components/TimeLine.vue]: What isn't needed?

File: src/components/TimeLine.vue (hunk 5 above)
Comment (gotdairyya) [reply src/components/TimeLine.vue]: Not sure what the suggestion is

File: src/components/TimeSlicing.vue (hunk 10 above)
Comment (gotdairyya) [reply src/components/TimeSlicing.vue:235]: It is a manual process

File: src/components/TimeSlicing.vue (hunk 8 above)
Comment (gotdairyya) [reply src/components/TimeSlicing.vue]: Resolved

File: src/components/DragTarget.vue (hunk 3 above)
Comment (gotdairyya) [reply src/components/DragTarget.vue]: Resolved

File: src/App.vue (hunk 2 above)
Comment (gotdairyya) [reply src/App.vue]: Resolved

File: src/components/TimeSlicing.vue (hunk 9 above)
Comment (gotdairyya) [reply src/components/TimeSlicing.vue]: Wow yeah that code was so unnecessarily complicated -- let me know what you think of the simplified version

**Comment by gotdairyya** [comment]
I created a new issue #7 so that we can merge to main and I can get feedback from collaborators while working on simplifying the code

File: src/components/TimeLine.vue (hunk 4 above)
Comment (JackWilb) [reply src/components/TimeLine.vue]: You don't use it anywhere in the TS and it's not mandatory. I've removed it in 96b4982

File: src/components/TimeLine.vue (hunk 5 above)
Comment (JackWilb) [reply src/components/TimeLine.vue]: You use `:class="currentTime.current === index ? 'timelineRectClass selected' : 'timelineRectClass'"` to toggle whether or not the element is `selected`. I'm saying that in the TS chunk here, you could instead just set `currentTime.current` to get the selected class. Shouldn't setting `currentTime.current = 0`, do the same as this code?

File: src/components/TimeSlicing.vue (hunk 6 above)
Comment (JackWilb) [reply src/components/TimeSlicing.vue]: See a52eb1d

File: src/components/TimeSlicing.vue (hunk 9 above)
Comment (JackWilb) [reply src/components/TimeSlicing.vue]: Looks much better 😄

**Review by JackWilb — CHANGES_REQUESTED** [review]
2 comments to resolve still. I also want to make a note that we're duplicating the controls logic, too, for some of these components. Would you open an issue for that?

**Comment by gotdairyya** [comment]
> 2 comments to resolve still. I also want to make a note that we're duplicating the controls logic, too, for some of these components. Would you open an issue for that?

Yes, that has now been recorded in issue #8

File: src/components/TimeLine.vue (hunk 5 above)
Comment (gotdairyya) [reply src/components/TimeLine.vue]: You're so right! Just simplified it.

**Review by JackWilb — APPROVED** [review]
Looks good! Thanks Derya
